services:
  - type: web
    name: whatshells-store-api
    env: node
    plan: free
    rootDir: store_api
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
